### ISSUE TITLE
在T10或者V100环境下，无论是docker部署还是直接部署均报错

### ISSUE THREAD

**Issue by Marione-tte** [XiaoMi/xiaomi-miloco#93]
在T10或者V100环境下，无论是docker部署还是直接部署均报错
测试环境
T10/V100
ubuntu 24.04
CUDA 使用过 12.5.1/12.8/12.9/
驱动使用过 555/560/570
环境直接跑和docker内跑都有如下错误
两张显卡均报如下错误

/app/third_party/llama.cpp/ggml/src/ggml-cuda/ggml-cuda.cu:75: CUDA error
ggml_cuda_compute_forward: RMS_NORM failed
CUDA error: no kernel image is available for execution on the device
  current device: 0, in function ggml_cuda_compute_forward at /app/third_party/llama.cpp/ggml/src/ggml-cuda/ggml-cuda.cu:2362
  err
/app/output/lib/libggml-base.so(+0x1588b)[0x7bd89002088b]
/app/output/lib/libggml-base.so(ggml_print_backtrace+0x21c)[0x7bd890020cec]
/app/output/lib/libggml-base.so(ggml_abort+0xef)[0x7bd890020e3f]
/app/output/lib/libggml-cuda.so(_Z15ggml_cuda_errorPKcS0_S0_iS0_+0xb7)[0x7bd872f912f7]
/app/output/lib/libggml-cuda.so(+0xcf3bf)[0x7bd872f9f3bf]
/app/output/lib/libggml-base.so(ggml_backend_sched_graph_compute_async+0x483)[0x7bd890036c93]
/app/output/lib/libllama.so(_ZN13llama_context13graph_computeEP11ggml_cgraphb+0xa1)[0x7bd8901dcb11]
/app/output/lib/libllama.so(_ZN13llama_context14process_ubatchERK12llama_ubatch14llm_graph_typeP20llama_memory_state_iR11ggml_status+0x103)[0x7bd8901dd113]
/app/output/lib/libllama.so(_ZN13llama_context6decodeERK11llama_batch+0x3be)[0x7bd8901e0b8e]
/app/output/lib/libllama.so(llama_decode+0xf)[0x7bd8901e1ddf]
/app/miloco_ai_engine/core_python/../../output/lib/libllama-mico.so(_Z23common_init_from_paramsR13common_params+0x6ca)[0x7bd8906978ea]
/app/miloco_ai_engine/core_python/../../output/lib/libllama-mico.so(_ZN16LlamaMicoContextC2ER13common_params+0x3f)[0x7bd8905a958f]
/app/miloco_ai_engine/core_python/../../output/lib/libllama-mico.so(llama_mico_init+0xd5)[0x7bd890595ff5]
/usr/lib/x86_64-linux-gnu/libffi.so.8(+0x7b16)[0x7bd8bef4ab16]
/usr/lib/x86_64-linux-gnu/libffi.so.8(+0x43ef)[0x7bd8bef473ef]
/usr/lib/x86_64-linux-gnu/libffi.so.8(ffi_call+0x12e)[0x7bd8bef4a0be]
/usr/lib/python3.12/lib-dynload/_ctypes.cpython-312-x86_64-linux-gnu.so(+0xe11c)[0x7bd8bef5d11c]
/usr/lib/python3.12/lib-dynload/_ctypes.cpython-312-x86_64-linux-gnu.so(+0x92af)[0x7bd8bef582af]
python3(_PyObject_MakeTpCall+0x75)[0x5492f5]
python3(_PyEval_EvalFrameDefault+0xadf)[0x5d68bf]
python3[0x66b079]
/usr/lib/python3.12/lib-dynload/_asyncio.cpython-312-x86_64-linux-gnu.so(+0x9d44)[0x7bd8bf07bd44]

<img width="1174" height="745" alt="Image" src="https://github.com/user-attachments/assets/34f8e317-0b85-4d7a-b55d-de8987204d76" />

**Comment by Marione-tte** [comment]
前端没有问题，只有AI引擎有问题

**Comment by Marione-tte** [comment]
我这边解决了，所有不支持的可以修改ai_engine_cuda_build.sh 里面 CUDA_ARCS="70;75" # default 30xx/40xx/50xx
部分来支持比较老的显卡
